name: test-and-docs
on: [push, pull_request]

permissions:
  contents: write
  pull-requests: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim:
          - 'stable'
          # - "devel"
    name: Nim ${{ matrix.nim }} test
    steps:
      - uses: actions/checkout@v3
      - name: Setup nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run: nimble --verbose -y test
  pretty:
    needs: build-test
    runs-on: ubuntu-latest
    name: Nim pretty
    steps:
      - uses: actions/checkout@master
      - uses: jiro4989/setup-nim-action@v1
      - uses: juancarlospaco/nimpretty-action@main
        with:
          maxLineLen: 120
  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim:
          - 'stable'
          # - "devel"
    name: Nim ${{ matrix.nim }} docsgen
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docs
        shell: bash
        run: |
          branch=${{ github.ref }}
          branch=${branch##*/}
          nimble --verbose doc2 --project --outdir:htmldocs --index:only -y \
            '-d:docgen' \
            '--git.url:https://github.com/${{ github.repository }}' \
            '--git.commit:${{ github.sha }}' \
            "--git.devel:$branch" \
            "./nim_norg.nim" || true
          nimble --verbose doc2 --project --outdir:htmldocs -y \
            '-d:docgen' \
            '--git.url:https://github.com/${{ github.repository }}' \
            '--git.commit:${{ github.sha }}' \
            "--git.devel:$branch" \
            "./nim_norg.nim"
          cp ./htmldocs/{nim_norg,index}.html || true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./htmldocs
